// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item is one line of the report.
 */
export interface Item {
    "group": string;
    "key": string;
    "status": string;

    /**
     * Value is translated ("diag.items.<key>.<value>") with Args filled in;
     * empty when Text says it all.
     */
    "value"?: string;
    "args"?: { [_ in string]?: string } | null;

    /**
     * Text is shown as it is: a version, a path.
     */
    "text"?: string;

    /**
     * Detail is shown as it is, under "diag.items.<key>.detail": the RD
     * Gateway server, the servers a policy lists.
     */
    "detail"?: string;

    /**
     * Private: Detail names something of the user's, such as a server on
     * their network. Copies of the report, meant for bug reports, leave it
     * out.
     */
    "private"?: boolean;
}
