// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Line is one log line. Msg is a stable key (session lines, which the UI
 * translates) or plain English text.
 */
export interface Line {
    "time": string;
    "level": string;
    "source": string;

    /**
     * the profile ID of a session line
     */
    "profile"?: string;
    "msg": string;
    "args"?: { [_ in string]?: any } | null;

    /**
     * Seq numbers the lines of a log in the order they were kept, so the UI
     * can merge a log it read with the lines it was sent. The app's log
     * (Logger) and the session logs, across all profiles, count apart.
     */
    "seq"?: number;
}
