// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings are the user's application preferences (settings.json).
 */
export interface Settings {
    "schema": number;

    /**
     * Language is empty until the user picks one on first launch; the UI then
     * shows the language picker instead of the main window.
     */
    "language": string;
    "theme": string;
    "closeBehavior": string;
    "localPort": number;
    "checkRouteBeforeConnect": boolean;
    "testUrl": string;
    "logLevel": string;
}
