// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Display is how the remote desktop is shown.
 */
export interface Display {
    "mode": string;

    /**
     * Width and Height apply to DisplayWindow. They are kept while another
     * mode is selected, so switching back restores them.
     */
    "width": number;
    "height": number;

    /**
     * Multimon and Span apply to DisplayFullscreen and exclude each other.
     * Multimon gives the remote session one monitor per local monitor; Span
     * stretches a single remote desktop across all of them.
     */
    "multimon": boolean;
    "span": boolean;
}

/**
 * FieldError is one problem with one field. Field is the field's JSON path,
 * such as "target.host"; Code is one of the Code constants.
 */
export interface FieldError {
    "field": string;
    "code": string;
}

/**
 * Profile is one remote computer the user connects to (profiles\<id>.json).
 */
export interface Profile {
    "schema": number;
    "id": string;
    "name": string;

    /**
     * Group sorts profiles into sections in the list; empty means none.
     */
    "group": string;
    "target": Target;

    /**
     * ProxyID is the proxy the tunnel goes through, or DirectProxyID.
     */
    "proxyId": string;

    /**
     * Loopback is the profile's own tunnel entrance, 127.a.b.c (see package
     * loopback). It is assigned once when the profile is created.
     */
    "loopback": string;

    /**
     * Username pre-fills the Remote Desktop sign-in: DOMAIN\user or
     * user@domain.
     */
    "username": string;

    /**
     * RememberPassword keeps a password entered in this app in Windows
     * Credential Manager. When it is false, a password entered for one
     * connection is deleted again when that session ends.
     */
    "rememberPassword": boolean;
    "display": Display;

    /**
     * Admin connects to the server's administrative session (mstsc /admin).
     */
    "admin": boolean;
}

/**
 * Proxy is a way to reach targets (proxies\<id>.json). Many profiles can use
 * the same proxy, so switching to another server is done in one place.
 */
export interface Proxy {
    "schema": number;
    "id": string;
    "name": string;
    "kind": string;

    /**
     * Server and Port locate the proxy server. For KindXray they are only
     * shown in lists; the outbound decides where connections go.
     */
    "server": string;
    "port": number;

    /**
     * Username signs in to a SOCKS5 or HTTP proxy, with Secret as the
     * password.
     */
    "username": string;

    /**
     * Secret is what signs in: the password of a SOCKS5, HTTP, Shadowsocks,
     * Trojan or Hysteria2 proxy, or the user ID of a VMess or VLESS one. The
     * store seals it with DPAPI before it writes the file.
     */
    "secret": string;

    /**
     * Options are the settings of the V2Ray-family kinds (IsV2Ray) besides
     * the server, the port and the secret. They include obfuscation keys and
     * the paths that lead to the server, so the store seals them like Secret.
     */
    "options": ProxyOptions;

    /**
     * Outbound is the complete Xray outbound object, as JSON text, of a
     * KindXray proxy. It holds credentials, so the store seals it like
     * Secret.
     */
    "outbound": string;
}

/**
 * ProxyOptions are a V2Ray-family proxy's settings besides the server, the
 * port and the secret: the protocol's own options, the transport and its
 * security layer. Most are named after the share-link parameters of the same
 * meaning (XTLS/Xray-core discussion #716).
 * 
 * Normalize keeps only the options that apply to the proxy's kind, network
 * and security, and fills in the defaults, so what is stored is exactly what
 * is used.
 */
export interface ProxyOptions {
    /**
     * Cipher is Shadowsocks' method (ShadowsocksCiphers), or VMess' own
     * encryption, which Xray calls "security" (VMessCiphers).
     */
    "cipher": string;

    /**
     * Flow is VLESS' flow control (VLESSFlows); empty for none.
     */
    "flow": string;

    /**
     * Encryption is VLESS' encryption: "none", or the client setting of VLESS
     * Encryption ("mlkem768x25519plus.…").
     */
    "encryption": string;

    /**
     * ObfsPassword turns on Hysteria2's Salamander obfuscation.
     */
    "obfsPassword": string;

    /**
     * Network is how VMess, VLESS and Trojan carry the connection (Networks).
     */
    "network": string;

    /**
     * HeaderType disguises TCP as HTTP (TCPHeaders), or mKCP packets as
     * another protocol (KCPHeaders).
     */
    "headerType": string;

    /**
     * Host and Path are the HTTP host and path of WebSocket, HTTPUpgrade and
     * XHTTP, and of TCP's HTTP disguise, where both are comma-separated
     * lists. For mKCP's DNS disguise, Host is the domain.
     */
    "host": string;
    "path": string;

    /**
     * ServiceName and Authority are gRPC's.
     */
    "serviceName": string;
    "authority": string;

    /**
     * Mode is gRPC's (GRPCModes) or XHTTP's (XHTTPModes).
     */
    "mode": string;

    /**
     * Seed encrypts mKCP packets with AES-128-GCM; without it they are only
     * obfuscated.
     */
    "seed": string;

    /**
     * Extra is XHTTP's further settings, a JSON object.
     */
    "extra": string;

    /**
     * FinalMask is Xray's "finalmask" settings (masks for the packets on the
     * wire, QUIC parameters), a JSON object; share links call it "fm".
     */
    "finalMask": string;

    /**
     * Security is the layer around the transport: SecurityNone, SecurityTLS
     * or SecurityREALITY.
     */
    "security": string;

    /**
     * SNI is the server name that TLS and REALITY present. Empty means the
     * server's address (TLS only).
     */
    "sni": string;

    /**
     * ALPN is TLS' application protocols, comma-separated.
     */
    "alpn": string;

    /**
     * Fingerprint is the TLS client that TLS and REALITY imitate, such as
     * "chrome" (Fingerprints); empty is Xray's default, Chrome.
     */
    "fingerprint": string;

    /**
     * PinnedCerts are the SHA-256 hashes, in hex, of the certificates to
     * trust, comma-separated. They are the way to trust a self-signed
     * certificate: Xray no longer skips verification ("allowInsecure").
     */
    "pinnedCerts": string;

    /**
     * VerifyNames are the names to verify the certificate against instead of
     * the SNI, comma-separated.
     */
    "verifyNames": string;

    /**
     * ECH is the config list of TLS Encrypted Client Hello.
     */
    "ech": string;

    /**
     * PublicKey, ShortID, SpiderX and MLDSA65Verify are REALITY's.
     */
    "publicKey": string;
    "shortId": string;
    "spiderX": string;
    "mldsa65Verify": string;
}

/**
 * Settings are the user's application preferences (settings.json).
 */
export interface Settings {
    "schema": number;

    /**
     * Language is empty until the user picks one on first launch; the UI then
     * shows the language picker instead of the main window.
     */
    "language": string;
    "theme": string;
    "closeBehavior": string;
    "localPort": number;
    "checkRouteBeforeConnect": boolean;
    "testUrl": string;
    "logLevel": string;
}

/**
 * Target is the remote computer a connection reaches through its proxy.
 */
export interface Target {
    /**
     * Host is a DNS name or an IP address, without brackets or a port.
     */
    "host": string;
    "port": number;
}
