// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Display is how the remote desktop is shown.
 */
export interface Display {
    "mode": string;

    /**
     * Width and Height apply to DisplayWindow. They are kept while another
     * mode is selected, so switching back restores them.
     */
    "width": number;
    "height": number;

    /**
     * Multimon and Span apply to DisplayFullscreen and exclude each other.
     * Multimon gives the remote session one monitor per local monitor; Span
     * stretches a single remote desktop across all of them.
     */
    "multimon": boolean;
    "span": boolean;
}

/**
 * FieldError is one problem with one field. Field is the field's JSON path,
 * such as "target.host"; Code is one of the Code constants.
 */
export interface FieldError {
    "field": string;
    "code": string;
}

/**
 * Profile is one remote computer the user connects to (profiles\<id>.json).
 */
export interface Profile {
    "schema": number;
    "id": string;
    "name": string;

    /**
     * Group sorts profiles into sections in the list; empty means none.
     */
    "group": string;
    "target": Target;

    /**
     * ProxyID is the proxy the tunnel goes through, or DirectProxyID.
     */
    "proxyId": string;

    /**
     * Loopback is the profile's own tunnel entrance, 127.a.b.c (see package
     * loopback). It is assigned once when the profile is created.
     */
    "loopback": string;

    /**
     * Username pre-fills the Remote Desktop sign-in: DOMAIN\user or
     * user@domain.
     */
    "username": string;

    /**
     * RememberPassword keeps a password entered in this app in Windows
     * Credential Manager. When it is false, a password entered for one
     * connection is deleted again when that session ends.
     */
    "rememberPassword": boolean;
    "display": Display;

    /**
     * Admin connects to the server's administrative session (mstsc /admin).
     */
    "admin": boolean;
}

/**
 * Proxy is a way to reach targets (proxies\<id>.json). Many profiles can use
 * the same proxy, so switching to another server is done in one place.
 */
export interface Proxy {
    "schema": number;
    "id": string;
    "name": string;
    "kind": string;

    /**
     * Server and Port locate the proxy server. For KindXray they are only
     * shown in lists; the outbound decides where connections go.
     */
    "server": string;
    "port": number;

    /**
     * Username and Secret sign in to a SOCKS5 or HTTP proxy. The store seals
     * Secret with DPAPI before it writes the file.
     */
    "username": string;
    "secret": string;

    /**
     * Outbound is the complete Xray outbound object, as JSON text, for the
     * V2Ray-family kinds and KindXray. It holds credentials, so the store
     * seals it like Secret.
     */
    "outbound": string;
}

/**
 * Settings are the user's application preferences (settings.json).
 */
export interface Settings {
    "schema": number;

    /**
     * Language is empty until the user picks one on first launch; the UI then
     * shows the language picker instead of the main window.
     */
    "language": string;
    "theme": string;
    "closeBehavior": string;
    "localPort": number;
    "checkRouteBeforeConnect": boolean;
    "testUrl": string;
    "logLevel": string;
}

/**
 * Target is the remote computer a connection reaches through its proxy.
 */
export interface Target {
    /**
     * Host is a DNS name or an IP address, without brackets or a port.
     */
    "host": string;
    "port": number;
}
