// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as api$0 from "../../../../liubz102/RDP-over-proxy/internal/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as diag$0 from "../../../../liubz102/RDP-over-proxy/internal/diag/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as logging$0 from "../../../../liubz102/RDP-over-proxy/internal/logging/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../liubz102/RDP-over-proxy/internal/model/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:notice": api$0.Notice;
            "app:quitRequested": api$0.QuitView;
            "data:changed": api$0.DataView;
            "diag:changed": diag$0.Item[] | null;
            "session:log": logging$0.Line;
            "sessions:changed": api$0.SessionView;
            "settings:changed": model$0.Settings;
        }
    }
}
