// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../liubz102/RDP-over-proxy/internal/model/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "settings:changed": model$0.Settings;
        }
    }
}
