// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Candidate is a port on this computer that may be a proxy.
 */
export interface Candidate {
    /**
     * Name is how people know the program: a known app ("v2rayN") that
     * listens itself or started the program that listens, else the
     * listening program's file name without ".exe" ("xray"); empty when
     * the program is not known.
     */
    "name": string;

    /**
     * Hosts are the addresses that reach the port, the one to prefer
     * first. A socket listening on every IPv6 address takes IPv4
     * connections too unless it was made IPv6-only, which the socket table
     * does not tell, so both loopback addresses are listed for it.
     */
    "hosts": string[] | null;
    "port": number;
    "source": string;
}

/**
 * Result is how a port answered a SOCKS5 greeting.
 */
export interface Result {
    /**
     * Socks5: it is a SOCKS5 server the app can use, one that lets anyone
     * in or one that wants a user name and password (Password).
     */
    "socks5": boolean;
    "password": boolean;

    /**
     * Host is the address that took the connection, one of those asked.
     */
    "host": string;
}
