// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Note is something about a link the user should know: a parameter the
 * proxy does without, or one that changes what it does. The UI translates
 * "linkNotes.<code>" with Args filled in.
 */
export interface Note {
    "code": string;
    "args"?: { [_ in string]?: string } | null;
}
