// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService is about the app as a whole: notices, its own log, quitting.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logging$0 from "../logging/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dismiss removes a notice.
 */
export function Dismiss(id: number): $CancellablePromise<void> {
    return $Call.ByID(934932723, id);
}

/**
 * KeepRunning answers a request to quit with "no": the user cancelled the
 * confirmation.
 */
export function KeepRunning(): $CancellablePromise<void> {
    return $Call.ByID(1134588247);
}

/**
 * Log returns the app's recent log lines, oldest first, with nothing
 * masked: they are for the user's own screen.
 */
export function Log(): $CancellablePromise<logging$0.Line[] | null> {
    return $Call.ByID(3122046705);
}

/**
 * Notices returns the notices not yet dismissed, oldest first. Notices that
 * arrive later come as EventNotice.
 */
export function Notices(): $CancellablePromise<$models.Notice[] | null> {
    return $Call.ByID(2339793414);
}

/**
 * Quit quits the app. Quitting ends every remote desktop, so while any is
 * connected an unconfirmed request only reports how many, and the UI asks
 * the user before calling again with confirmed.
 */
export function Quit(confirmed: boolean): $CancellablePromise<$models.QuitView> {
    return $Call.ByID(3920790614, confirmed);
}
