// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagService reports what on this computer affects Remote Desktop
 * connections, and opens the places where it is changed. It never changes a
 * setting itself.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diag$0 from "../diag/models.js";

/**
 * EditDefaults opens Remote Desktop Connection on Default.rdp, where the
 * settings every connection shares are changed and saved. It returns once
 * mstsc has started.
 */
export function EditDefaults(): $CancellablePromise<void> {
    return $Call.ByID(1532508769);
}

/**
 * OpenLogs shows the log folder in File Explorer, for attaching the log to
 * a bug report. The log file has names and addresses masked.
 */
export function OpenLogs(): $CancellablePromise<void> {
    return $Call.ByID(2877749476);
}

/**
 * Report gathers the environment report anew, item by item in the order of
 * the groups. It only reads. Until WMI has said whether Credential Guard
 * runs, that item says it is being checked, and EventDiagChanged brings the
 * report again once it has.
 */
export function Report(): $CancellablePromise<diag$0.Item[] | null> {
    return $Call.ByID(3198198685);
}
