// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes the running build for the About section.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "repo": string;
}
