// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * AppInfo describes the running build for the About section.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "repo": string;
}

/**
 * CheckView is the result of a route check.
 */
export interface CheckView {
    "elapsedMs": number;

    /**
     * Protocol is the security protocol the server chose, such as
     * "HYBRID_EX"; empty when NegotiationFailure is set.
     */
    "protocol": string;

    /**
     * NegotiationFailure is why the server refused every protocol offered,
     * such as "SSL_REQUIRED_BY_SERVER". The route works all the same.
     */
    "negotiationFailure"?: string;
}

/**
 * ConnectResult is what Connect did.
 */
export interface ConnectResult {
    /**
     * Focused: the connection was already running, so its window was
     * brought to the front instead.
     */
    "focused": boolean;
}

/**
 * DataView is every profile and proxy, sent with EventDataChanged.
 */
export interface DataView {
    "profiles": ProfileView[] | null;
    "proxies": ProxyView[] | null;
}

/**
 * ErrorView is how an error reaches the UI: a code to translate
 * ("errors.<code>"), the error's own text as details, and, for validation
 * errors, the fields to mark.
 */
export interface ErrorView {
    "code": string;
    "message": string;
    "fields"?: model$0.FieldError[] | null;

    /**
     * Args fill in the translated message, such as the names of the
     * connections that still use a proxy.
     */
    "args"?: { [_ in string]?: string } | null;
}

/**
 * LatencyResult is a proxy latency test's result.
 */
export interface LatencyResult {
    "ms": number;
}

/**
 * Notice is something the user should know about that no button press of
 * theirs caused, such as a file that could not be loaded. It stays until
 * dismissed.
 */
export interface Notice {
    "id": number;
    "level": string;

    /**
     * Code is translated ("notices.<code>"), with Args filled in.
     */
    "code": string;
    "args"?: { [_ in string]?: string } | null;
    "message"?: string;
}

/**
 * ProfileView is a profile as the UI lists it.
 */
export interface ProfileView {
    "profile": model$0.Profile;

    /**
     * PasswordSaved: the app remembers a password for this connection.
     */
    "passwordSaved": boolean;

    /**
     * PasswordByMstsc: mstsc itself remembers one ("Remember me" in its
     * sign-in prompt).
     */
    "passwordByMstsc": boolean;

    /**
     * ProxyMissing: the profile's proxy no longer exists.
     */
    "proxyMissing": boolean;
}

/**
 * ProxyView is a proxy as the UI lists it. Secret and Outbound, which both
 * hold credentials, are always empty; ProxyService.Get returns the outbound.
 */
export interface ProxyView {
    "proxy": model$0.Proxy;

    /**
     * HasSecret: a password is stored.
     */
    "hasSecret": boolean;

    /**
     * BuiltIn: the direct entry, which cannot be edited or deleted.
     */
    "builtIn": boolean;

    /**
     * UsedBy counts the profiles that use the proxy.
     */
    "usedBy": number;
}

/**
 * SessionView is a session's state as the UI shows it.
 */
export interface SessionView {
    "profileId": string;

    /**
     * Phase is preparing, checking, launching, running, ending or ended.
     */
    "phase": string;
    "step": string;

    /**
     * Outcome is set once the phase is ended: closed, cancelled or failed.
     */
    "outcome": string;

    /**
     * Failure and FailedStep say why a failed session ended.
     */
    "failure": ErrorView | null;
    "failedStep": string;

    /**
     * Addr is the tunnel entrance mstsc connects to.
     */
    "addr": string;
    "pid": number;
    "exitCode": number;

    /**
     * Conns counts mstsc's open connections through the tunnel.
     */
    "conns": number;

    /**
     * Upstream is unknown, ok or failing; UpstreamError is the latest reason
     * a connection could not reach the target.
     */
    "upstream": string;
    "upstreamError": ErrorView | null;

    /**
     * TunnelError is set when the entrance stopped accepting connections.
     */
    "tunnelError": ErrorView | null;
    "check": CheckView | null;
}
