// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService manages the connection profiles and their saved passwords.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create stores a new profile. When password is set and the profile
 * remembers passwords, it is saved in Windows Credential Manager. A
 * password that cannot be saved does not undo the profile; a notice says
 * so.
 */
export function Create(p: model$0.Profile, password: string): $CancellablePromise<$models.ProfileView> {
    return $Call.ByID(314568711, p, password);
}

/**
 * Delete removes a profile, its saved passwords and what mstsc remembers
 * about its address. A connected profile cannot be deleted.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1125492156, id);
}

/**
 * Draft returns the starting values for a new profile. ID, Name, Target and
 * ProxyID are for the user to fill in.
 */
export function Draft(): $CancellablePromise<model$0.Profile> {
    return $Call.ByID(2774807018);
}

/**
 * ForgetPassword deletes every saved password of the profile: the app's
 * and the one mstsc remembered.
 */
export function ForgetPassword(id: string): $CancellablePromise<void> {
    return $Call.ByID(3269240923, id);
}

/**
 * List returns every profile, by group and name.
 */
export function List(): $CancellablePromise<$models.ProfileView[] | null> {
    return $Call.ByID(2041236007);
}

/**
 * Update stores the edited profile. Its ID and loopback address stay.
 * 
 *   - Changing the target computer (host or port) deletes the saved
 *     passwords: they belong to the old computer, and mstsc would offer them
 *     to the new one.
 *   - A new password replaces the saved one; an empty password keeps it.
 *   - Turning "remember password" off deletes the password the app saved.
 *   - A new user name moves the app's saved password to that name.
 */
export function Update(p: model$0.Profile, password: string): $CancellablePromise<$models.ProfileView> {
    return $Call.ByID(4110691726, p, password);
}
