// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService manages the proxies.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create stores a new proxy, once Xray has accepted its settings.
 */
export function Create(p: model$0.Proxy): $CancellablePromise<$models.ProxyView> {
    return $Call.ByID(2199925662, p);
}

/**
 * Delete removes a proxy. The profiles that use it switch to the built-in
 * direct entry, but only those in moveToDirect, the ones the user was shown
 * and agreed to: any other user leaves everything as it was, and the error
 * (proxy.inUse) names them in its args ("profiles") so the user can be
 * asked again. Nothing changes either while a connected profile uses the
 * proxy (ErrProxyConnected).
 */
export function Delete(id: string, moveToDirect: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3030182293, id, moveToDirect);
}

/**
 * DraftLatency is Latency through settings that are not saved, such as a
 * link just pasted into the editor. With keepSecret the stored proxy's
 * secret is used (p.ID names it), as Update would. The settings are checked
 * as Create and Update check them.
 */
export function DraftLatency(p: model$0.Proxy, keepSecret: boolean): $CancellablePromise<$models.LatencyResult> {
    return $Call.ByID(560764533, p, keepSecret);
}

/**
 * Get returns one proxy for editing, without its secret (see HasSecret in
 * List). Its options and custom outbound come along: the editor shows them.
 */
export function Get(id: string): $CancellablePromise<model$0.Proxy> {
    return $Call.ByID(2115052486, id);
}

/**
 * Latency fetches the test URL (Settings.TestURL) through the proxy and
 * reports how long it took. It waits as long as the route takes; the
 * frontend cancels the call to stop it.
 */
export function Latency(id: string): $CancellablePromise<$models.LatencyResult> {
    return $Call.ByID(2598322760, id);
}

/**
 * List returns the built-in direct entry first, then every proxy by name.
 * Passwords are left out.
 */
export function List(): $CancellablePromise<$models.ProxyView[] | null> {
    return $Call.ByID(58848486);
}

/**
 * ParseLink reads a share link into a proxy for the editor to fill in;
 * nothing is saved. The notes say what the link asks for that the proxy does
 * without.
 */
export function ParseLink(link: string): $CancellablePromise<$models.LinkView> {
    return $Call.ByID(434563073, link);
}

/**
 * ShareLink writes a stored proxy as a share link, credentials included, for
 * the user to copy.
 */
export function ShareLink(id: string): $CancellablePromise<string> {
    return $Call.ByID(3867526709, id);
}

/**
 * Update stores an edited proxy, once Xray has accepted its settings. With
 * keepSecret the stored secret stays and p.Secret is ignored, so the form
 * does not need to know it; a proxy that changes its kind keeps none.
 * While a connected profile uses the proxy it is not changed
 * (ErrProxyConnected): that session would go on with the old settings.
 */
export function Update(p: model$0.Proxy, keepSecret: boolean): $CancellablePromise<$models.ProxyView> {
    return $Call.ByID(2399689955, p, keepSecret);
}
