// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyService manages the proxies.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create stores a new proxy.
 */
export function Create(p: model$0.Proxy): $CancellablePromise<$models.ProxyView> {
    return $Call.ByID(2199925662, p);
}

/**
 * Delete removes a proxy. One that connections still use is not removed;
 * the error's args name them ("profiles").
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3030182293, id);
}

/**
 * Get returns one proxy for editing, without its password (see HasSecret
 * in List).
 */
export function Get(id: string): $CancellablePromise<model$0.Proxy> {
    return $Call.ByID(2115052486, id);
}

/**
 * Latency fetches the test URL (Settings.TestURL) through the proxy and
 * reports how long it took. It waits as long as the route takes; the
 * frontend cancels the call to stop it.
 */
export function Latency(id: string): $CancellablePromise<$models.LatencyResult> {
    return $Call.ByID(2598322760, id);
}

/**
 * List returns the built-in direct entry first, then every proxy by name.
 * Passwords are left out.
 */
export function List(): $CancellablePromise<$models.ProxyView[] | null> {
    return $Call.ByID(58848486);
}

/**
 * Update stores an edited proxy. With keepSecret the stored password stays
 * and p.Secret is ignored, so the form does not need to know it. Sessions
 * already using the proxy keep the settings they started with.
 */
export function Update(p: model$0.Proxy, keepSecret: boolean): $CancellablePromise<$models.ProxyView> {
    return $Call.ByID(2399689955, p, keepSecret);
}
