// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService connects, disconnects and checks routes. Progress arrives
 * as EventSessionsChanged and EventSessionLog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logging$0 from "../logging/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckRoute checks that the profile's target answers as an RDP server
 * through its proxy, without starting Remote Desktop. It waits as long as
 * the route takes; the frontend cancels the call to stop it.
 */
export function CheckRoute(profileID: string): $CancellablePromise<$models.CheckView> {
    return $Call.ByID(3217212443, profileID);
}

/**
 * CheckRouteVia is CheckRoute along the way SystemRoute said Windows' proxy
 * setting takes the profile's connection. The route check shows that way
 * and checks it, rather than asking Windows again, which could take as long
 * once more and answer differently.
 */
export function CheckRouteVia(profileID: string, via: $models.RouteView): $CancellablePromise<$models.CheckView> {
    return $Call.ByID(3420416513, profileID, via);
}

/**
 * Connect starts a session for the profile and returns at once. When the
 * profile is already connected, its window comes to the front instead.
 * 
 * password, when set, is used for this connection: a profile that remembers
 * passwords saves it as its password; otherwise it is kept for this session
 * only and deleted when the session ends.
 */
export function Connect(profileID: string, password: string): $CancellablePromise<$models.ConnectResult> {
    return $Call.ByID(1124127208, profileID, password);
}

/**
 * Disconnect ends the profile's session. Before mstsc runs it cancels;
 * afterwards it asks mstsc to close, which may ask the user to confirm.
 * force ends mstsc instead.
 */
export function Disconnect(profileID: string, force: boolean): $CancellablePromise<void> {
    return $Call.ByID(3203334252, profileID, force);
}

/**
 * Focus brings the profile's Remote Desktop window to the front.
 */
export function Focus(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1719289022, profileID);
}

/**
 * Log returns the log of the profile's latest session, oldest line first.
 */
export function Log(profileID: string): $CancellablePromise<logging$0.Line[] | null> {
    return $Call.ByID(3398330432, profileID);
}

/**
 * States returns the latest state of every session since the app started,
 * ended ones included.
 */
export function States(): $CancellablePromise<$models.SessionView[] | null> {
    return $Call.ByID(1644988164);
}

/**
 * SystemRoute says how Windows' proxy setting takes the profile's
 * connection now. It is for profiles that follow the setting; the route
 * check shows it, then checks that way (CheckRouteVia). Running the
 * automatic configuration, when one is set, takes as long as the network
 * does; the frontend cancels the call to stop it.
 */
export function SystemRoute(profileID: string): $CancellablePromise<$models.RouteView> {
    return $Call.ByID(145704064, profileID);
}
