// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService reads and saves the user's preferences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppInfo returns the product name, version and repository URL.
 */
export function AppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(2413417640);
}

/**
 * Get returns the settings in effect. An empty Language means the user has not
 * picked one yet; the UI then shows the language picker first.
 */
export function Get(): $CancellablePromise<model$0.Settings> {
    return $Call.ByID(3143047199);
}

/**
 * Save validates and stores new settings, then tells the shell and every
 * window about them. It returns the settings as stored (defaults filled in).
 */
export function Save($in: model$0.Settings): $CancellablePromise<model$0.Settings> {
    return $Call.ByID(4015766016, $in);
}

/**
 * SystemLanguage suggests the UI language that matches the Windows display
 * language: "zh-CN" for any Chinese variant, otherwise "en".
 */
export function SystemLanguage(): $CancellablePromise<string> {
    return $Call.ByID(2685399134);
}
