// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Server is a proxy server: model.KindHTTP, which tunnels with CONNECT, or
 * model.KindSocks.
 */
export interface Server {
    "kind": string;
    "host": string;
    "port": number;
}

/**
 * Settings are the current user's Internet proxy settings.
 */
export interface Settings {
    /**
     * AutoDetect: "Automatically detect settings" (WPAD).
     */
    "autoDetect": boolean;

    /**
     * Script is the setup script's address ("Use setup script"), or "".
     */
    "script": string;

    /**
     * Proxy is the manual proxy server while it is on, as Windows keeps it:
     * "host:port" for every protocol, or "http=host:port;https=…;socks=…";
     * else "".
     */
    "proxy": string;

    /**
     * Bypass lists the addresses the manual proxy is not used for:
     * "localhost;127.*;*.example.com;<local>".
     */
    "bypass": string;
}
